### ISSUE TITLE
Adding a new repository does not show up in web interface

### ISSUE THREAD

**Issue by geekbozu** [ikus060/rdiffweb#69]
Backing up a new folder into an existing users root directory does not update the repository list without re-applying the users root directory. 

Python 3.7.4
rdiffweb 1.2.1

I even tried a reboot and this was the only way to get it to show up.

**Comment by ikus060** [comment]
I will need more information regarding what are the step you done and what is the expected behaviour.

Take note, rdiffweb has a limited integration with rdiff-backup and will not auto refresh the repositories. You need to wait for the daemon task to refresh the repositories automatically or you need to go into the users profile and click the "refresh repositories" button.

**Comment by geekbozu** [comment]
Gladly,
I did not realize it was updating via a daemon, That might be the larger issue as I was expecting it to show more immediately. 

I also missed the refresh repository button. 
This is a non issue just me missing information.  Sorry about that. Closing!

**Comment by ikus060** [comment]
Will try to improve the interface to help new user understand they need to "refresh" the repositories.
See https://git.patrikdufresne.com/pdsl/rdiffweb/issues/77
